server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/fundering;MODE=MySQL
#    url: jdbc:mariadb://localhost:3307/krampoline
    url: jdbc:h2:mem:test;MODE=MySQL
    username: root
    password: passwd
    driver-class-name: org.h2.Driver
#    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      use_sql_comments: true
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              MariaDBDialect:
        highlight_sql: true
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

  sql:
    init:
      encoding: utf-8
  data:
    redis:
      host: localhost
      port: 6379
logging.level:
  org.hibernate.SQL: debug
springdoc:
  use-fqn: true
  # org.hibernate.type: trace